FROM ruby:3.3

# Instalación de dependencias necesarias
RUN apt-get update -qq && apt-get install -y build-essential default-mysql-client default-libmysqlclient-dev git netcat-openbsd
RUN git config --global http.sslVerify false
RUN apt remove cmdtest -y
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash
RUN apt-get install nodejs
RUN npm install -g npm@latest
RUN npm install -g yarn

# Configuración del directorio de trabajo
WORKDIR /tfm

# Copia de dependencias de Ruby
COPY Gemfile /tfm/Gemfile
COPY Gemfile.lock /tfm/Gemfile.lock
RUN bundle install

# Copia del resto de los archivos de la aplicación
COPY . /tfm

# Variables de entorno necesarias para la configuración
ARG PROD_DATABASE_PWD
ENV PROD_DATABASE_PWD=$PROD_DATABASE_PWD
ARG PROD_DATABASE_PORT
ENV PROD_DATABASE_PORT=$PROD_DATABASE_PORT
ARG PROD_DATABASE_URL
ENV PROD_DATABASE_URL=$PROD_DATABASE_URL
ARG PROD_DATABASE_USR
ENV PROD_DATABASE_USR=$PROD_DATABASE_USR
ARG RAILS_MASTER_KEY
ENV RAILS_MASTER_KEY=$RAILS_MASTER_KEY

# Precompilación de activos
RUN bundle exec rake assets:precompile RAILS_ENV=development

# Configuración de scripts de entrada
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

# Exposición del puerto
EXPOSE 3000

# Creación de directorios necesarios
RUN mkdir -p /tfm/tmp/pids

# Comando final para iniciar el servidor
CMD ["bundle", "exec", "puma", "config.ru"]