# syntax=docker/dockerfile:1
FROM --platform=linux/amd64 ruby:3.1.3
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash
RUN apt-get update -qq && apt-get install -y build-essential libmariadb-dev-compat libmariadb-dev pip nodejs
RUN apt remove cmdtest -y
RUN python3 -m pip install pandas matplotlib
RUN python3 -m pip install -U scikit-learn
RUN npm install -g npm@latest
RUN npm install -g yarn
WORKDIR /tfg
COPY . /tfg
RUN bundle install

ARG PROD_DATABASE_PWD
ENV PROD_DATABASE_PWD=$PROD_DATABASE_PWD
ARG PROD_DATABASE_PORT
ENV PROD_DATABASE_PORT=$PROD_DATABASE_PORT
ARG PROD_DATABASE_URL
ENV PROD_DATABASE_URL=$PROD_DATABASE_URL
ARG PROD_DATABASE_USR
ENV PROD_DATABASE_USR=$PROD_DATABASE_USR
ARG RAILS_MASTER_KEY
ENV RAILS_MASTER_KEY=$RAILS_MASTER_KEY

RUN bundle exec rails db:create RAILS_ENV=production
RUN bundle exec rails db:migrate RAILS_ENV=production
RUN bundle exec rake assets:precompile RAILS_ENV=production

EXPOSE 3000
CMD bundle exec rails server -b 0.0.0.0 -p $PORT -e production